### ISSUE TITLE
Would be happy to make some simple sound effects/music

### ISSUE THREAD

**Issue by Daniel-Griffiths** [Flet/HerpFortress#1]
The game is still very basic but what its really lacking is sound, im not good enough at java to implement it myself but I would be happy to make some simple sound effects and maybe even music if somebody could implemented it. :)

**Comment by Daniel-Griffiths** [comment]
Quickly re-made the tf2 theme but made it sounds retroish. https://dl.dropbox.com/u/13594612/tf2.ogg

**Comment by Softizo** [comment]
I have some experience in java, and I will like to add the music in the game that you posted, but the game doesn't load the asset for me for some reason. I'm assuming that the music would run.

**Comment by Flet** [comment]
@Softizo I created this repository mostly just to save a copy of HerpFortress for future generations.

Feel free to fork this repo and hack away if you're interested in continuing its development. I won't be accepting any new code on this repo.
